### ISSUE TITLE
TypeError: buffer is too small for requested array

### ISSUE THREAD

**Issue by mxzf0213** [reu2018DL/YOLO-LITE#10]
Excuse me, I'm new here. 
I try to convert  your project's tiny-yolov2-trial3-noBatch.cfg and tiny-yolov2-trial3-noBatch.weights into .h5 with yad2k.py, but I get the error 'Traceback (most recent call last):
  File "yad2k.py", line 270, in <module>
    _main(parser.parse_args())
  File "yad2k.py", line 156, in _main
    buffer=weights_file.read(weights_size * 4))
TypeError: buffer is too small for requested array'.
BTW, I'm confused that it's ok when I change the files using tiny-yolov2-trial3.cfg and tiny-yolov2-trial3.weights, can you explain what's wrong?

**Comment by xautzxc** [comment]
@mxzf0213 are u sovle it?Thanks
